### ISSUE TITLE
Could not create Virtual Source with name...

### ISSUE THREAD

**Issue by alexbuga** [Air-Craft/MIDIFish#1]
I have the following code and when I open the app I get this error:
"Terminating app due to uncaught exception 'MFNonFatalException', reason: "Could not create Virtual Source with name ABMidiTest"

<code>
class ViewController: UIViewController {

  var midiSession: MFMIDISession!

  override func viewDidLoad() {
    super.viewDidLoad()

```
midiSession = MFMIDISession(name: "ABMidiTest")
midiSession.networkEnabled = true
midiSession.restorePreviousConnectionStates = true
midiSession.autoEnableDestinations = true
midiSession.channel = 1
midiSession.createVirtualSourceWithName(midiSession.name)
```

  }

  @IBAction func didPressNote() {
    midiSession.sendNoteOn(64, velocity: 120)
  }
}
</code>

**Comment by QuinnFrederick** [comment]
Hi,

Thanks for that. Can you catch the exception and print out it's
`osStatusAsString` method?

Here's the code that causes the issues. What device are you using this on?:

osStatusAsStringMIDIEndpointRef endpoint;

```
_MFCheckErr(MIDISourceCreate(_clientRef,

                             (__bridge CFStringRef)name,

                             &endpoint),

            @"Could not create Virtual Source with name %@", name);



echo("Creating MIDI Source with endpoint %i for Virtual Source with
```

name \"%@\"", (int)endpoint, name);

Gratefully,

Hari Karam Singh

http://air-craft.co/?utm_source=emailsig-ac1-logo&utm_medium=email-signature&utm_campaign=air-craft-general
The future of musical artistry...

_Watch the demo (~1m) »_
http://air-craft.co/?utm_source=emailsig-ac1-video&utm_medium=email-signature&utm_campaign=air-craft-general

http://air-craft.co
http://air-craft.co/?utm_source=emailsig-ac1-website&utm_medium=email-signature&utm_campaign=air-craft-general
 · 0779 055 6418 · London SE1

**Comment by alexbuga** [comment]
Its the same on both simulator and iPhone 6s
I'll try catching that. Let's see if I manage to do that :)

**Comment by alexbuga** [comment]
Can't seem to figure out how to catch that.

**Comment by alexbuga** [comment]
osStatus    OSStatus    -10844  -10844
Rings a bell ?

**Comment by QuinnFrederick** [comment]
Hey i found this:
http://stackoverflow.com/questions/12548856/coremidi-pgmidi-virtual-midi-error-in-ios6

Let me know if it works...

HKS

On Wednesday, 11 November 2015, alexbuga notifications@github.com wrote:

> osStatus OSStatus -10844 -10844
> Rings a bell ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Air-Craft/MIDIFish/issues/1#issuecomment-155830671.

## 

http://air-craft.co/?utm_source=emailsig-ac1-logo&utm_medium=email-signature&utm_campaign=air-craft-general
The future of musical artistry...

_Watch the demo (~1m) »_
http://air-craft.co/?utm_source=emailsig-ac1-video&utm_medium=email-signature&utm_campaign=air-craft-general

http://air-craft.co
http://air-craft.co/?utm_source=emailsig-ac1-website&utm_medium=email-signature&utm_campaign=air-craft-general
 · 0779 055 6418 · London SE1

**Comment by alexbuga** [comment]
Holy smokes! IT WORKS !!!
Thanks!

**Comment by QuinnFrederick** [comment]
Awesome. Rock on...

http://air-craft.co/?utm_source=emailsig-ac1-logo&utm_medium=email-signature&utm_campaign=air-craft-general
The future of musical artistry...

_Watch the demo (~1m) »_
http://air-craft.co/?utm_source=emailsig-ac1-video&utm_medium=email-signature&utm_campaign=air-craft-general

http://air-craft.co
http://air-craft.co/?utm_source=emailsig-ac1-website&utm_medium=email-signature&utm_campaign=air-craft-general
 · 0779 055 6418 · London SE1

**Comment by alexbuga** [comment]
I do have a question though. It connects via Wifi to my Mac but it doesn't send MIDI. It just sends inter app on my device. Am I missing something?
Thank you.

**Comment by QuinnFrederick** [comment]
Hey Alex,

Sorry for the delay. Does your mac show up in the network scan.
networkConnections property after waiting a while or use the delegate
methods to catch them.

I've noticed discoverability has been a bit broken since iOS9 and El
Capitan. I'm working to get Apple to take a look.  Usually its resolved by
cycling wifi on/off on OSX or rebooting the phone or the machine.

Let me know how you get on...

Gratefully,
Hari Karam Singh

http://air-craft.co/?utm_source=emailsig-ac1-logo&utm_medium=email-signature&utm_campaign=air-craft-general
The future of musical artistry...

_Watch the demo (~1m) »_
http://air-craft.co/?utm_source=emailsig-ac1-video&utm_medium=email-signature&utm_campaign=air-craft-general

http://air-craft.co
http://air-craft.co/?utm_source=emailsig-ac1-website&utm_medium=email-signature&utm_campaign=air-craft-general
 · 0779 055 6418 · London SE1

**Comment by alexbuga** [comment]
I connect the iPhone to the Mac via Audio Midi Utility
It shows up and I click connect.
Should I have a connection panel in the App also where I need to connect to
the Mac? I set autoEnable to true so I thought it should do it
automatically.
I'll try the delegate methods but yeah the problem might be with the way El
Capitan deals with that.
Thanks.

**Comment by QuinnFrederick** [comment]
After you click "connect" does it timeout after a while with an error?  If
so, connect again. It used to be such that the second time it would work
due to another bug in OSX which I reported a while back and I think they
fixed but who knows...

Also make sure you aren't running Cloak or any other kind of VPN or
firewall as this messes with the connectivity just as described.  Try doing
a tethered connection too. Enable Wifi Hotspot on your iDevice and connect
the macbook to it.

Here's another way to use bluetooth:
https://developer.apple.com/library/mac/qa/qa1831/_index.html  It will come
up as an endpointConnection

HKS

http://air-craft.co/?utm_source=emailsig-ac1-logo&utm_medium=email-signature&utm_campaign=air-craft-general
The future of musical artistry...

_Watch the demo (~1m) »_
http://air-craft.co/?utm_source=emailsig-ac1-video&utm_medium=email-signature&utm_campaign=air-craft-general

http://air-craft.co
http://air-craft.co/?utm_source=emailsig-ac1-website&utm_medium=email-signature&utm_campaign=air-craft-general
 · 0779 055 6418 · London SE1

**Comment by alexbuga** [comment]
Will try. Thanks.
